services:
  cpa:
    image: eceasy/cli-proxy-api:v7.2.42@sha256:6684c2a604eb900d00a5225f56e5e8ad4dea224529eaa1a9790b55b0e27e4ff0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD}
      PGSTORE_DSN: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8317"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
