services:
  metapi:
    image: 1467078763/metapi:latest@sha256:d29e74b18ce0734555c2088f1f6638e301a7fc01873ff979961ff8a1ac618da8
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${PANEL_APP_PORT_HTTP}:4000"
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      PROXY_TOKEN: ${PROXY_TOKEN}
      CHECKIN_CRON: ${CHECKIN_CRON}
      BALANCE_REFRESH_CRON: ${BALANCE_REFRESH_CRON}
      PORT: 4000
      DATA_DIR: /app/data
      TZ: Asia/Shanghai
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
