services:
  anheyu:
    image: anheyu/pro:1.8.16@sha256:fc94b1881a9b65ef820983af7e0c2da1e1f2503a66884e35200b92c51f352b78
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:8091
    environment:
      ANHEYU_DATABASE_TYPE: postgres
      ANHEYU_DATABASE_HOST: ${PANEL_DB_HOST}
      ANHEYU_DATABASE_USER: ${PANEL_DB_USER}
      ANHEYU_DATABASE_NAME: ${PANEL_DB_NAME}
      ANHEYU_DATABASE_PORT: ${PANEL_DB_PORT}
      ANHEYU_DATABASE_PASSWORD: ${PANEL_DB_USER_PASSWORD}
      ANHEYU_REDIS_ADDR: ${PANEL_REDIS_HOST}:6379
      ANHEYU_REDIS_PASSWORD: ${PANEL_REDIS_ROOT_PASSWORD}
      ANHEYU_REDIS_DB: 10
      ANHEYU_LICENSE_KEY: ${PANEL_LICENSE_KEY}
    networks:
      - 1panel-network

    volumes:
      - ./data:/anheyu/data
      - ./themes:/anheyu/themes
      - ./static:/anheyu/static
      - ./backup:/anheyu/backup
      
networks:
  1panel-network:
    external: true
