services:
  octopus:
    image: bestrui/octopus:v0.9.28@sha256:26025ed4af3b7ea2ee40b234cabc381a662ee38eb0cb443a716559fec4f99603
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    environment:
      OCTOPUS_DATABASE_TYPE: postgres
      OCTOPUS_DATABASE_PATH: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}?sslmode=disable
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
