services:
  cpa:
    image: eceasy/cli-proxy-api:v7.2.130@sha256:7fca20b67690f919d88a868e3dcfcba8bbda5f42fef9e5169c0b95853ff6fb8c
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD}
      PGSTORE_DSN: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8317"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
